import React from "react";

import Table from "react-bootstrap/Table";

import "./hiragana.styles.scss";

const Hiragana = () => (
  <>
    <Table responsive>
      <thead>
        <tr>
          <th>n</th>
          <th>w-</th>
          <th>r-</th>
          <th>y-</th>
          <th>m-</th>
          <th>h-</th>
          <th>n-</th>
          <th>t-</th>
          <th>s-</th>
          <th>k-</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div>ん</div>(N)
          </td>
          <td>
            <div>わ</div>(WA)
          </td>
          <td>
            <div>ら</div>(RA)
          </td>
          <td>
            <div>や</div>(YA)
          </td>
          <td>
            <div>ま</div>(MA)
          </td>
          <td>
            <div>は</div>(HA)
          </td>
          <td>
            <div>な</div>(NA)
          </td>
          <td>
            <div>た</div>(TA)
          </td>
          <td>
            <div>さ</div>(SA)
          </td>
          <td>
            <div>か</div>(KA)
          </td>
          <td>
            <div>あ</div>(A)
          </td>
          <th>-a</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ら</div>(RI)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>み</div>(MI)
          </td>
          <td>
            <div>ひ</div>(HI)
          </td>
          <td>
            <div>に</div>(NI)
          </td>
          <td>
            <div>ち</div>(CHI)
          </td>
          <td>
            <div>し</div>(SHI)
          </td>
          <td>
            <div>き</div>(KI)
          </td>
          <td>
            <div>い</div>(I)
          </td>
          <th>-i</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>る</div>(RU)
          </td>
          <td>
            <div>ゆ</div>(YU)
          </td>
          <td>
            <div>む</div>(MU)
          </td>
          <td>
            <div>ふ</div>(FU)
          </td>
          <td>
            <div>ぬ</div>(NU)
          </td>
          <td>
            <div>つ</div>(TSU)
          </td>
          <td>
            <div>す</div>(SU)
          </td>
          <td>
            <div>く</div>(KU)
          </td>
          <td>
            <div>う</div>(U)
          </td>
          <th>-u</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>れ</div>(RE)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>め</div>(ME)
          </td>
          <td>
            <div>へ</div>(HE)
          </td>
          <td>
            <div>ね</div>(NE)
          </td>
          <td>
            <div>て</div>(TE)
          </td>
          <td>
            <div>せ</div>(SE)
          </td>
          <td>
            <div>け</div>(KE)
          </td>
          <td>
            <div>え</div>(E)
          </td>
          <th>-e</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div>を</div>(WO)
          </td>
          <td>
            <div>ろ</div>(RO)
          </td>
          <td>
            <div>よ</div>(YO)
          </td>
          <td>
            <div>も</div>(MO)
          </td>
          <td>
            <div>ほ</div>(HO)
          </td>
          <td>
            <div>の</div>(NO)
          </td>
          <td>
            <div>と</div>(TO)
          </td>
          <td>
            <div>そ</div>(SO)
          </td>
          <td>
            <div>こ</div>(KO)
          </td>
          <td>
            <div>を</div>(O)
          </td>
          <th>-o</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ば/ぱ</div>(BA/PA)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>だ</div>(DA)
          </td>
          <td>
            <div>ざ</div>(ZA)
          </td>
          <td>
            <div>が</div>(GA)
          </td>
          <td>
            <div></div>
          </td>
          <th>a"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>び/ぴ</div>(BI/PI)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ぢ</div>(JI)
          </td>
          <td>
            <div>じ</div>(JI)
          </td>
          <td>
            <div>ぎ</div>(GI)
          </td>
          <td>
            <div></div>
          </td>
          <th>i"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ぶ/ぷ</div>(BU/PU)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>づ</div>(ZU)
          </td>
          <td>
            <div>ず</div>(ZU)
          </td>
          <td>
            <div>ぐ</div>(GU)
          </td>
          <td>
            <div></div>
          </td>
          <th>u"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>べ/ぺ</div>(BE/PE)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>で</div>(DE)
          </td>
          <td>
            <div>ぜ</div>(ZE)
          </td>
          <td>
            <div>げ</div>(GE)
          </td>
          <td>
            <div></div>
          </td>
          <th>e"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ぼ/ぽ</div>(BO/PO)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ど</div>(DO)
          </td>
          <td>
            <div>ぞ</div>(ZO)
          </td>
          <td>
            <div>ご</div>(GO)
          </td>
          <td>
            <div></div>
          </td>
          <th>o"</th>
        </tr>
      </tbody>
    </Table>
    <br />
    <Table responsive>
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th>ry-</th>
          <th></th>
          <th>my-</th>
          <th>hy-</th>
          <th>ny-</th>
          <th>ch-</th>
          <th>sh-</th>
          <th>ky-</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>りゃ</div>(RYA)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>みゃ</div>(MYA)
          </td>
          <td>
            <div>ひゃ</div>(HYA)
          </td>
          <td>
            <div>にゃ </div>(NYA)
          </td>
          <td>
            <div>ちゃ</div>(CHA)
          </td>
          <td>
            <div>しゃ</div>(SHA)
          </td>
          <td>
            <div>きゃ</div>(KYA)
          </td>
          <td>
            <div></div>
          </td>
          <th>-a</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>りゅ</div>(RYU)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>みゅ</div>(MYU)
          </td>
          <td>
            <div>ひゅ</div>(HYU)
          </td>
          <td>
            <div>にゅ</div>(NYU)
          </td>
          <td>
            <div>ちゅ</div>(CHU)
          </td>
          <td>
            <div>しゅ</div>(SHU)
          </td>
          <td>
            <div>きゅ</div>(KYU)
          </td>
          <td>
            <div></div>
          </td>
          <th>-u</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>りょ</div>(RYO)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>みょ</div>(MYO)
          </td>
          <td>
            <div>ひょ</div>(HYO)
          </td>
          <td>
            <div>にょ</div>(NYO)
          </td>
          <td>
            <div>ちょ</div>(CHO)
          </td>
          <td>
            <div>しょ</div>(SHO)
          </td>
          <td>
            <div>きょ</div>(KYO)
          </td>
          <td>
            <div></div>
          </td>
          <th>-o</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>びゃ/ぴゃ</div>(BYA/PYA)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>じゃ</div>(JA)
          </td>
          <td>
            <div>ぎゃ</div>(GYA)
          </td>
          <td>
            <div></div>
          </td>
          <th>a"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>びゅ/ぴゅ</div>(BYU/PYU)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>じゅ</div>(JU)
          </td>
          <td>
            <div>ぎゅ</div>(GYU)
          </td>
          <td>
            <div></div>
          </td>
          <th>u"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ぴょ/びょ</div>(BYO/PYO)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>じょ</div>(JO)
          </td>
          <td>
            <div>ぎょ</div>(GYO)
          </td>
          <td>
            <div></div>
          </td>
          <th>o"</th>
        </tr>
      </tbody>
    </Table>
  </>
);

export default Hiragana;
