import React from "react";

import Table from "react-bootstrap/Table";

import "./katakana.styles.scss";

const Katakana = () => (
  <>
    <Table responsive>
      <thead>
        <tr>
          <th>n</th>
          <th>w-</th>
          <th>r-</th>
          <th>y-</th>
          <th>m-</th>
          <th>h-</th>
          <th>n-</th>
          <th>t-</th>
          <th>s-</th>
          <th>k-</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div>ン</div>(N)
          </td>
          <td>
            <div>ワ</div>(WA)
          </td>
          <td>
            <div>ラ</div>(RA)
          </td>
          <td>
            <div>ヤ</div>(YA)
          </td>
          <td>
            <div>マ</div>(MA)
          </td>
          <td>
            <div>ハ</div>(HA)
          </td>
          <td>
            <div>ナ</div>(NA)
          </td>
          <td>
            <div>タ</div>(TA)
          </td>
          <td>
            <div>サ</div>(SA)
          </td>
          <td>
            <div>カ</div>(KA)
          </td>
          <td>
            <div>ア</div>(A)
          </td>
          <th>-a</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>リ</div>(RI)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ミ</div>(MI)
          </td>
          <td>
            <div>ヒ</div>(HI)
          </td>
          <td>
            <div>ニ</div>(NI)
          </td>
          <td>
            <div>チ</div>(CHI)
          </td>
          <td>
            <div>シ</div>(SHI)
          </td>
          <td>
            <div>キ</div>(KI)
          </td>
          <td>
            <div>イ</div>(I)
          </td>
          <th>-i</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ル</div>(RU)
          </td>
          <td>
            <div>ユ</div>(YU)
          </td>
          <td>
            <div>ム</div>(MU)
          </td>
          <td>
            <div>フ</div>(FU)
          </td>
          <td>
            <div>ヌ</div>(NU)
          </td>
          <td>
            <div>ツ</div>(TSU)
          </td>
          <td>
            <div>ス</div>(SU)
          </td>
          <td>
            <div>ク</div>(KU)
          </td>
          <td>
            <div>ウ</div>(U)
          </td>
          <th>-u</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>レ</div>(RE)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>メ</div>(ME)
          </td>
          <td>
            <div>へ</div>(HE)
          </td>
          <td>
            <div>ネ</div>(NE)
          </td>
          <td>
            <div>テ</div>(TE)
          </td>
          <td>
            <div>セ</div>(SE)
          </td>
          <td>
            <div>ケ</div>(KE)
          </td>
          <td>
            <div>エ</div>(E)
          </td>
          <th>-e</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div>ヲ</div>(WO)
          </td>
          <td>
            <div>ロ</div>(RO)
          </td>
          <td>
            <div>ヨ</div>(YO)
          </td>
          <td>
            <div>モ</div>(MO)
          </td>
          <td>
            <div>ホ</div>(HO)
          </td>
          <td>
            <div>ノ</div>(NO)
          </td>
          <td>
            <div>ト</div>(TO)
          </td>
          <td>
            <div>ソ</div>(SO)
          </td>
          <td>
            <div>コ</div>(KO)
          </td>
          <td>
            <div>オ</div>(O)
          </td>
          <th>-o</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>バ/パ</div>(BA/PA)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ダ</div>(DA)
          </td>
          <td>
            <div>ザ</div>(ZA)
          </td>
          <td>
            <div>ガ</div>(GA)
          </td>
          <td>
            <div></div>
          </td>
          <th>a"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ビ/ピ</div>(BI/PI)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ヂ</div>(JI)
          </td>
          <td>
            <div>ジ</div>(JI)
          </td>
          <td>
            <div>ギ</div>(GI)
          </td>
          <td>
            <div></div>
          </td>
          <th>i"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ブ/プ</div>(BU/PU)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ヅ</div>(ZU)
          </td>
          <td>
            <div>ズ</div>(ZU)
          </td>
          <td>
            <div>グ</div>(GU)
          </td>
          <td>
            <div></div>
          </td>
          <th>u"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ベ/ペ</div>(BE/PE)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>デ</div>(DE)
          </td>
          <td>
            <div>ゼ</div>(ZE)
          </td>
          <td>
            <div>ゲ</div>(GE)
          </td>
          <td>
            <div></div>
          </td>
          <th>e"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ボ/ポ</div>(BO/PO)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ド</div>(DO)
          </td>
          <td>
            <div>ゾ</div>(ZO)
          </td>
          <td>
            <div>ゴ</div>(GO)
          </td>
          <td>
            <div></div>
          </td>
          <th>o"</th>
        </tr>
      </tbody>
    </Table>
    <br />
    <Table responsive>
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th>ry-</th>
          <th></th>
          <th>my-</th>
          <th>hy-</th>
          <th>ny-</th>
          <th>ch-</th>
          <th>sh-</th>
          <th>ky-</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>リャ</div>(RYA)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>リャ</div>(MYA)
          </td>
          <td>
            <div>ヒャ</div>(HYA)
          </td>
          <td>
            <div>ニャ</div>(NYA)
          </td>
          <td>
            <div>チャ</div>(CHA)
          </td>
          <td>
            <div>シャ</div>(SHA)
          </td>
          <td>
            <div>キャ</div>(KYA)
          </td>
          <td>
            <div></div>
          </td>
          <th>-a</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>リュ</div>(RYU)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ミュ</div>(MYU)
          </td>
          <td>
            <div>ヒュ</div>(HYU)
          </td>
          <td>
            <div>ニュ</div>(NYU)
          </td>
          <td>
            <div>チュ</div>(CHU)
          </td>
          <td>
            <div>シュ</div>(SHU)
          </td>
          <td>
            <div>キュ</div>(KYU)
          </td>
          <td>
            <div></div>
          </td>
          <th>-u</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>リョ</div>(RYO)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ミョ</div>(MYO)
          </td>
          <td>
            <div>ヒョ</div>(HYO)
          </td>
          <td>
            <div>ニョ</div>(NYO)
          </td>
          <td>
            <div>チョ</div>(CHO)
          </td>
          <td>
            <div>ショ</div>(SHO)
          </td>
          <td>
            <div>キョ</div>(KYO)
          </td>
          <td>
            <div></div>
          </td>
          <th>-o</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ビャ/ピャ</div>(BYA/PYA)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ジャ</div>(JA)
          </td>
          <td>
            <div>ギャ</div>(GYA)
          </td>
          <td>
            <div></div>
          </td>
          <th>a"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ビュ/ピュ</div>(BYU/PYU)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ジュ</div>(JU)
          </td>
          <td>
            <div>ギュ</div>(GYU)
          </td>
          <td>
            <div></div>
          </td>
          <th>u"</th>
        </tr>
        <tr>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ビョ/ピョ</div>(BYO/PYO)
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div></div>
          </td>
          <td>
            <div>ジョ</div>(JO)
          </td>
          <td>
            <div>ギョ</div>(GYO)
          </td>
          <td>
            <div></div>
          </td>
          <th>o"</th>
        </tr>
      </tbody>
    </Table>
  </>
);

export default Katakana;
